backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/assets/images" # Location where files will be stored in the repo
public_folder: "/assets/images" # The src attribute for uploaded media
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "discription", widget: "string" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Thumbnail", name: "image", widget: "image", default: "default-thumbnail.jpg" }
      - label: "Thumbnail"
      name: "image"
      widget: "object"
      collapsed: true
      fields: 
        - {label: "Image", name: "url", widget: "image", default: "default-thumbnail.jpg" }
        - {label: "Alt", name: "alt", widget: "string", default: "Channel Banner" }
      - { label: "Author", name: "author", widget: "string", default: "Altie" }
      - { label: "Tags", name: "tags", widget: "select", multiple: true, options: ["Code", "Personal-life", "Gaming", "Content", "Misc", "Projects"] }
      - { label: "Body", name: "body", widget: "markdown" }